// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.1
//   protoc               v5.26.1
// source: todo.proto

/* eslint-disable */

export const protobufPackage = "todo.definition";

export interface Todo {
  id: string;
  title: string;
  completed: boolean;
  description?: string | undefined;
}

export const TODO_DEFINITION_PACKAGE_NAME = "todo.definition";
